workspace:
  base: /go
  path: src/github.com/bigorn0/test-drone
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
